### ISSUE TITLE
Build fail in TravisCI from v1.5.1 on (zend/exception_handler.cpp - ‘tsrm_ls’ was not declared in this scope)

### ISSUE THREAD

**Issue by goddanao** [CopernicaMarketingSoftware/PHP-CPP#226]
Trying to build a php extension made with PHP-CPP on Travis CI with this configuration ends good with v1.5 and fail from v1.5.1 and on with several errors in zend/exception_handler.cpp
All the errors seems related to thread safety, the usage of macro EG raises ‘tsrm_ls’ was not declared in this scope.

.travis.yml
```yml
language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - composer self-update

install:
  - sudo apt-get install -qq g++-4.8 uuid-dev build-essential autoconf php5-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script:
  - git clone git://github.com/CopernicaMarketingSoftware/PHP-CPP.git && ( cd PHP-CPP; make -j4 && sudo make install && sudo ldconfig && cd ..)
```
